### ISSUE TITLE
How to seperate out a Consistfile?

### ISSUE THREAD

**Issue by reesericci** [consist-sh/consist#5]
I'm wondering if I can split out my Consistfile into many different files, say a files/ folder and a recipes/ folder, which can be imported into my Consistfile.

**Comment by jmdfm** [comment]
Yep it doesn't work that way right now, but there's no reason not to support this. It would definitely make maintenance more practical, but at the cost of losing the easy portability of having one giant Consistfile.

**Comment by jmdfm** [comment]
Working on this over in #6

**Comment by jmdfm** [comment]
Support added in https://github.com/consist-sh/consist/releases/tag/v0.1.3
